name: mrowid
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences_android: ^2.4.6
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  flutter_svg: ^2.0.17
  loading_animation_widget: ^1.3.0
  flutter_native_splash: ^2.4.4
  lottie: ^3.1.2
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.5.2
  table_calendar: ^3.2.0
  get: ^4.6.6
  flutter_slidable: ^3.0.1
  fluttertoast: ^8.2.8
  showcaseview: ^4.0.1

dev_dependencies:
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
          